config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  # get 'product/index'

  resources :products
  resources :users
  resources :admins
  resources :sales
  resources :categories
  resources :orders

  get '/admin', to: 'admins#inventory_index'

  get '/checkout', to: 'orders#update'

  get '/order_history', to: 'purchases#index'


  # get '/products/new', to: 'products#new'
  # post '/products', to: 'products#create'

  root 'products#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products
  has_many :categories
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :admin
  has_and_belongs_to_many :products
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :admin
  has_and_belongs_to_many :categories
  has_many :orders
  has_many :users, through: :orders

  before_create :round_price

  validates :name, :description, :list_price, :quantity, presence: true
  validates :list_price, numericality: { greater_than: 0 }
  validates :name, length: { maximum: 100 }
  validates :description, length: { maximum: 1000 }

  private
  def round_price
    self.list_price = self.list_price.round(2)
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :products, through: :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  def inventory_index
    @products = Product.all
  end

  def show
    redirect_to '/admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include ApplicationHelper

  def after_sign_in_path_for(resource)
    if resource.is_a? User
      user_path(current_user) #your path
    elsif resource.is_a? Admin
      admin_path(current_admin) #your path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @select_products = display_products(@category)
  end

  def new
    @category = current_admin.posts.build
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = current_admin.posts.build(category_params)

    if @category.save
      flash[:success] = "You successfully created a category!"
      redirect_to @category
    else
      flash[:danger] = "Sorry, we weren't able to create your category"
      render 'new'
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
    def category_params
      params.require(:category).permit(:name, :admin_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.where(user_id: current_user_id, purchased: nil)
  end

  def create
    order_new = Order.new(user_id: current_user_id, product_id: session[:product_id], quantity: params[:quantity])
    @orders = Order.where(user_id: current_user_id)
    order_quantity = params[:quantity].to_i
    checker = false
    if !@orders.empty?
      @orders.each do |order|
        if order.product_id == session[:product_id] && order.purchased == nil
          order.update(quantity: order.quantity + order_quantity)
          checker = true
        end
      end
      if checker == false
        order_new.save
        @orders << order_new
      end
    else
      order_new.save
    end

    if request.xhr?
      render '/orders/_index', layout: false, locals: { orders: @orders }
    else
      redirect_to '/'
    end

    # respond_to do |format|
    #   format.js
    #   format.html { redirect_to @orders, notice: 'order successfully created' }
    # end

    product = Product.find(session[:product_id])
    product.update(quantity: product.quantity - order_quantity)

  end

  def update
    orders = Order.where(user_id: current_user_id)
    orders.each do |order|
      order.update(purchased: true)
    end
    redirect_to '/orders/show'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @products = Product.all
    @categories = Category.all
  end

  def show
    @product = Product.find(params[:id])
    session[:product_id] = @product.id
  end

  def new
    @product = current_admin.posts.build
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = current_admin.posts.build(product_params)

    if @product.save
      flash[:success] = "You successfully listed your product!"
      redirect_to @product
    else
      flash[:danger] = "Sorry, we weren't able to list your product"
      render 'new'
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :description, :list_price, :quantity, :admin_id)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Order.where(purchased: true).reverse
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def create
    @sale = Sale.new(sale_name)

    if @sale.save
        redirect_to @sale
    else
      render 'new'
    end
  end

  def update
    @sale = Sale.find(params[:id])

    if @sale.update(sale_params)
      redirect_to @sale
    else
      render 'edit'
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy

    redirect_to sales_path
  end

  private
    def sale_params
      params.require(:sale).permit(:product_id, :buyer_id, :quantity, :total_amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        UserMailer.welcome_email(@user).deliver_now
        redirect_to '/'
      else
        render 'new'
      end
    end
  end



  private
    def user_params
      params.require(:user).permit(:email, :password)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_products(selected_category)
    category = Category.find(selected_category.id)
    category.products
  end

  def current_user_id
    session[:user_id] = User.find(session["warden.user.user.key"][0][0]).id
  end

  def calculate_price(order)
    order.quantity * order.product.list_price
  end
end

app/views/admins/inventory_index.html.haml
%h1 Products (Admin View)
%table{:cellpadding => "50"}
  %tr
    %th Name
    %th Quantity
    %th Price
  -@products.each do |product|
    %tr
      %td= link_to product.name, product
      %td= product.quantity
      %td= "$" + product.list_price.to_s
      %td= link_to 'Edit ', edit_product_path(product)
      %td= link_to ' Delete', product_path(product), method: :delete, data: { confirm: 'Are you sure?' }

%br
= link_to "New Product", new_product_path

app/views/categories/show.html.haml
%h1= @category.name
.col-md-3
  .list-group
  -@categories.each do |category|
    %a.list-group-item{:href => "/categories/#{category.id}"}= category.name


.container
  .row
    -@select_products.each do |product|
      .col-sm-3.col-lg-3.col-md-3
        .thumbnail
          %img{:alt => "", :src => product.img_link }
            .caption
              %h4.pull-right= "$" + product.list_price.to_s
              %br/
              %h4
                %a= link_to product.name, product
              %p= product.description[1..150] + '...'

app/views/layouts/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Ye Old Shop
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{:href => "#"} About
        %li
          %a{:href => "#"} Contact
        -if !admin_signed_in? && !user_signed_in?
          %li
            =link_to "Sign Up", new_user_registration_path
          %li
            =link_to "Sign In", new_user_session_path
          %li
            =link_to "Admin Sign In", new_admin_session_path
        -elsif user_signed_in?
          %li
            =link_to "View Cart", orders_path
          %li
            =link_to "Purchase History", order_history_path
          %li
            =link_to "Sign Out", destroy_user_session_path, method: :delete
        -elsif admin_signed_in?
          %li
            =link_to "Admin Sign Out", destroy_admin_session_path, method: :delete
    / /.navbar-collapse

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}

    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      %script{:src => "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{:src => "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"}
    %title Shoppe
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = yield

app/views/orders/_index.html.haml
.container.show
  .col-md-12
    %h1 Your Shopping Cart
    %table{:cellpadding => "50"}
      %tr
        %th Product
        %th Quantity
        %th Price
      - total = 0
      - orders.each do |order|
        -if order.purchased == nil
          %tr
            %td= link_to order.product.name, order.product
            %td= order.quantity
            - total += calculate_price(order)
            %td= "$" + calculate_price(order).to_s
    %h3= "Total: $" + total.round(2).to_s
    %a= link_to "View Cart"

app/views/orders/create.js.erb
$(".order-form").append("It worked")

app/views/orders/index.html.haml
.container.show
  .col-md-12
    %h1 Your Shopping Cart
    -if !@orders.empty?
      %table{:cellpadding => "50"}
        %tr
          %th Product
          %th Quantity
          %th Price
        - total = 0
        - @orders.each do |order|
          %tr
            %td= link_to order.product.name, order.product
            %td= order.quantity
            - total += calculate_price(order)
            %td= "$" + calculate_price(order).round(2).to_s
      %h3= "Total: $" + total.round(2).to_s
      =button_to("Checkout", checkout_path, method: :get)
    -else
      %h3 Your cart is empty
      = link_to "Return Home", products_path

app/views/orders/show.html.haml
%h1 You Checked out!!!!!!!!!
=link_to "Return Home", products_path
%br/
=link_to "View Order History", order_history_path

app/views/products/edit.html.haml
= form_for :product, url: product_path, method: :patch do |f|
  =f.label "Product Name"
  =f.text_field :name
  =f.label "Description"
  =f.text_field :description
  =f.label "Price"
  =f.number_field :list_price
  =f.label "Quantity in Stock"
  =f.number_field :quantity
  =f.submit

app/views/products/index.html.haml
%h1 Products
.col-md-3
  .list-group
  -@categories.each do |category|
    %a.list-group-item{:href => "/categories/#{category.id}"}= category.name


.container
  .row
    -@products.each do |product|
      .col-sm-3.col-lg-3.col-md-3
        .thumbnail
          %img{:alt => "", :src => product.img_link }
            .caption
              %h4.pull-right= "$" + product.list_price.to_s
              %br/
              %h4
                %a= link_to product.name, product
              %p= product.description[1..150] + '...'

app/views/products/new.html.haml
-flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message
= form_for :product, url: products_path do |f|
  - if @product.errors.any?
    .error_explanation
      %h2= pluralize(@product.errors.count, "error") + " prohibited this product from being saved"
    %ul
      - @product.errors.full_messages.each do |msg|
        %li= msg

  =f.label "Product Name"
  =f.text_field :name
  =f.label "Description"
  =f.text_field :description
  =f.label "Price"
  =f.text_field :list_price
  =f.label "Quantity in Stock"
  =f.number_field :quantity
  =f.submit

app/views/products/show.html.haml
-flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

.container.show
  .col-md-12.col-sm-12
    .thumbnail
      %img.img-responsive{:alt => "", :src => @product.img_link}
        .caption-full
          %h4.pull-right= "$" + @product.list_price.to_s
          %h4= @product.name
          %p= @product.description
          %ul
          -@product.categories.each do |category|
            %li
              =category.name
          %br/
          -if @product.quantity == 0
            %h3 SOLD OUT
          -else
          .order
            = form_for :order, url: orders_path, remote: true, method: :post, html: {class: "order-form"} do |f|
              %strong Select Quantity:
              %select{:name => "quantity"}
                - counter = 1
                - @product.quantity.times do
                  %option{:value => counter}= counter
                  - counter += 1
              %br/
              %br/
              -if current_user
                =f.submit "Add to Cart"
              -else
                =link_to "Sign in to Purchase", new_user_session_path

app/views/purchases/index.html.haml
.container.show
  .col-md-12
    %h1 Your Purchase History
    %table{:cellspacing => "15"}
      %tr
        %th Item
        %th Quantity
        %th Price
        %th Date
      - @purchases.each do |purchase|
        %tr
          %td= link_to purchase.product.name, purchase.product
          %td= purchase.quantity
          %td= "$" + calculate_price(purchase).round(2).to_s
          %td= purchase.created_at.strftime('%b %d, %Y')

app/views/users/show.html.haml
-flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

%link{:href => "http://fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet", :type => "text/css"}
  .container
    .fb-profile
      %img.fb-image-lg{:align => "left", :alt => "Profile image example", :src => "http://lorempixel.com/850/280/nightlife/5/"}/
      %img.fb-image-profile.thumbnail{:align => "left", :alt => "Profile image example", :src => "http://lorempixel.com/180/180/people/9/"}/
      .fb-profile-text
        %h1=@user.email
        %p Your shopping adventures!
  / /container